[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.8.0"
winit = "0.25.0"
winit_input_helper = "0.10.0"
